services:
  bot:
    build: 
      context: .
      dockerfile: Ledger/Dockerfile
    
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./Ledger
          target: /
          initial_sync: true

  dashboard:
    build: 
      context: .
      dockerfile: Dashboard/Dockerfile
    restart: always
    ports:
        - "5248:5248"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:5248
    develop:
      watch:
        - action: sync
          path: ./Dashboard
          target: /src/Dashboard
        - action: sync
          path: ./Database
          target: /src/Database
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
        - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U botty -d botty"]
      interval: 5s
      timeout: 5s
      retries: 5
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "7070:8080"
