FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["Botty/Botty.csproj", "Botty/"]
COPY ["Dashboard/Dashboard.csproj", "Dashboard/"]
COPY ["Database/Database.csproj", "Database/"]
# COPY ["Fluxer.Net/Fluxer.Net/Fluxer.Net.csproj", "Fluxer.Net/"]
RUN dotnet restore Botty/Botty.csproj
COPY Dashboard/ Dashboard/
COPY Database/ Database/
COPY Botty/ Botty/


WORKDIR "/src/Botty"
# RUN dotnet publish -c Release -o /app/out
ENTRYPOINT ["dotnet", "run", "--project", "."]
# FROM mcr.microsoft.com/dotnet/aspnet:10.0
# WORKDIR /app
# COPY --from=build /app/out .
# ENTRYPOINT ["dotnet", "Botty.dll"]

