FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs
WORKDIR /src
COPY ["Botty/Botty.csproj", "Botty/"]
COPY ["Dashboard/Dashboard.csproj", "Dashboard/"]
COPY ["Database/Database.csproj", "Database/"]
RUN dotnet restore Dashboard/Dashboard.csproj
COPY Dashboard/ Dashboard/
COPY Database/ Database/
COPY Botty/ Botty/


WORKDIR "/src/Dashboard"

ENTRYPOINT ["sh", "./entrypoint.sh"]
